# サイトの基本設定
title: JavaScript ハンズオン
description: 初心者のためのインタラクティブなJavaScript学習体験。電卓アプリ、ポモドーロタイマー、メモ帳アプリなどのハンズオンを通じて、JavaScriptの基本を学びます。
url: https://tomot7.github.io/javascript_handson
author: tomot7

# 言語とタイムゾーン設定
lang: ja
timezone: Asia/Tokyo

# プラグイン設定
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# カスタム変数
github_username: tomot7
github_repo: https://github.com/tomot7/javascript_handson